name: deploy pdf to s3

on:
  push:
    paths:
      - 'pdfs/**'

jobs:
  deploy-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: upload pdfs to s3
        run: |
          aws s3 cp pdfs/ s3://my-pdf-bucket --recursive
